# SPDX-License-Identifier: GPL-2.0
#
# Copyright 2021 Google LLC
#

# make $(src) as absolute path if it isn't already, by prefixing $(srctree)
src:=$(if $(patsubst /%,,$(src)),$(srctree)/$(src),$(src))

# Add include path for related GPU modules
ccflags-y += -I$(src)/../common/include

obj-$(CONFIG_MALI_PRIORITY_CONTROL_MANAGER) := mali_pcm.o
mali_pcm-objs := priority_control_manager.o
