#
# (C) COPYRIGHT 2012-2017 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
# SPDX-License-Identifier: GPL-2.0
#
#

mali_kbase-y += \
	$(MALI_PLATFORM_DIR)/pixel_gpu.o \
	$(MALI_PLATFORM_DIR)/pixel_gpu_power.o

mali_kbase-$(CONFIG_MALI_MIDGARD_DVFS) += \
	$(MALI_PLATFORM_DIR)/pixel_gpu_dvfs.o \
	$(MALI_PLATFORM_DIR)/pixel_gpu_dvfs_governor.o \
	$(MALI_PLATFORM_DIR)/pixel_gpu_dvfs_metrics.o \
	$(MALI_PLATFORM_DIR)/pixel_gpu_sysfs.o

mali_kbase-$(CONFIG_MALI_PIXEL_GPU_QOS) += \
	$(MALI_PLATFORM_DIR)/pixel_gpu_dvfs_qos.o

mali_kbase-$(CONFIG_MALI_PIXEL_GPU_THERMAL) += \
	$(MALI_PLATFORM_DIR)/pixel_gpu_tmu.o
